# swiftmailer:
#     url: '%env(MAILER_URL)%'
#     spool: { type: 'memory' }

swiftmailer:
    transport: 'smtp'
    host:      'smtp.gmail.com'
    username:  'keeppetcool@gmail.com'
    password:  'keeppetcool4!'
    port:      '587'
    encryption: 'tls'
