twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals:
        avatar_upload_path: 'avatar/'
        picture_upload_path: 'images/animal/'
        ws_server_ip: '%env(WS_SERVER_IP)%'
        ws_server_port: '%env(WS_SERVER_PORT)%'
        ws_server_secure: '%env(WS_SERVER_SECURE)%'
